export const en = {
  title: 'Title',
  description: 'Description',
  tags: 'Tags',
  type: 'Type',
  delete: 'Delete',
  edit: 'Edit',
  readMore: 'Read more',
  add: 'Add',
  color: 'Color',
  cancel: 'Cancel',
  confirm: 'Confirm',
  public: 'Public',
  owner: 'Owner',
  login: 'Login',
  deleteConfirmation: 'Are you sure to delete this note?',
  addToFavorites: 'Add to Favorites',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  changePassword: 'Change password',
  successMessage: 'Password successfully changed',
  enterEmail: 'Enter you email',
  enterPassword: 'Enter you password',
  welcomeBack: 'Welcome back',
  errorEmailRequired: 'Required',
  errorInvalidEmail: 'Invalid email',
  errorPasswordRequired: 'Required',
  private: 'Private',
  publicHeader: 'Public',
  showFavorites: 'Show only favorites',
  noFavorites: 'No notes added to favorites yet',
  errorNewPasswordInvalid: 'Password must be at least 6 characters long',
  errorPasswordsMustMatch: 'Passwords did not match',
}
