export const en = {
  title: 'Title',
  description: 'Description',
  tags: 'Tags',
  type: 'Type',
  delete: 'Delete',
  edit: 'Edit',
  readMore: 'Read more',
  add: 'Add',
  color: 'Color',
  cancel: 'Cancel',
  confirm: 'Confirm',
  public: 'Public',
  owner: 'Owner',
  login: 'Login',
  deleteConfirmation: 'Are you sure to delete this note?',
  addToFavorites: 'Add to Favorites',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  changePassword: 'Change password',
  successMessage: 'Password successfully changed',
}
