export const ru = {
  title: 'Название',
  description: 'Описание',
  tags: 'Тэги',
  type: 'Тип',
  delete: 'Удалить',
  edit: 'Редактировать',
  readMore: 'Подробнее',
  public: 'Публичный',
  cancel: 'Назад',
  color: 'Цвет',
  confirm: 'Подтвердить',
  add: 'Добавить',
  owner: 'Владелец',
  login: 'Войти',
  deleteConfirmation: 'Вы уверены, что хотите удалить эту заметку?',
  addToFavorites: 'Добавить в избранное',
  currentPassword: 'Текущий пароль',
  newPassword: 'Новый пароль',
  confirmPassword: 'Повторите пароль',
  changePassword: 'Изменить пароль',
  successMessage: 'Пароль успешно изменён',
  enterEmail: 'Введите почтовый адрес',
  enterPassword: 'Введите пароль',
  welcomeBack: 'C возвращением',
  errorEmailRequired: 'Обязательное поле',
  errorInvalidEmail: 'Неверный формат',
  errorPasswordRequired: 'Обязательное поле',
  private: 'Приватные',
  publicHeader: 'Публичные',
  showFavorites: 'Показать только избранные',
  noFavorites: 'Пока нет избранных заметок',
  errorNewPasswordInvalid: 'Пароль должен быть более 6 символов',
  errorPasswordsMustMatch: 'Пароли не совпадают',
}
